"""Removed extra fields from Quiz model

Revision ID: 5972993d7c57
Revises: ba45df612d06
Create Date: 2025-03-13 18:53:16.561084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5972993d7c57'
down_revision = 'ba45df612d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('randomize_questions', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('immediate_feedback', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('passing_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('deadline')
        batch_op.drop_column('passing_score')
        batch_op.drop_column('immediate_feedback')
        batch_op.drop_column('randomize_questions')
        batch_op.drop_column('time_limit')
        batch_op.drop_column('max_attempts')

    # ### end Alembic commands ###
