"""empty message

Revision ID: 7b335cea2e8b
Revises: 5ba0304b2825
Create Date: 2025-03-08 18:16:13.807549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b335cea2e8b'
down_revision = '5ba0304b2825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint('assignments_ibfk_2', type_='foreignkey')
        batch_op.drop_column('lesson_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('assignments_ibfk_2', 'course_lessons', ['lesson_id'], ['id'])

    # ### end Alembic commands ###
