"""Removed extra fields from Quiz model

Revision ID: b099e5067565
Revises: c42b3903d96e
Create Date: 2025-03-13 22:28:31.493898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b099e5067565'
down_revision = 'c42b3903d96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_answer_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('single_answer_questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('single_answer_questions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('quiz_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('question_text', mysql.TEXT(), nullable=False),
    sa.Column('correct_answer', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='single_answer_questions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('short_answer_questions')
    # ### end Alembic commands ###
