"""empty message

Revision ID: b48ab57cf957
Revises: 7b335cea2e8b
Create Date: 2025-03-09 14:15:32.136459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b48ab57cf957'
down_revision = '7b335cea2e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint('quizzes_ibfk_1', type_='foreignkey')
        batch_op.drop_column('lesson_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('quizzes_ibfk_1', 'course_lessons', ['lesson_id'], ['id'])

    # ### end Alembic commands ###
