"""Test migration with corrected URI

Revision ID: b714240ad229
Revises: 
Create Date: 2025-03-23 17:41:02.704067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b714240ad229'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_submissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_submissions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('assignment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('file_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('original_file_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('submitted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name='assignment_submissions_ibfk_1'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='assignment_submissions_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
