"""Removed extra fields from Quiz model

Revision ID: ba45df612d06
Revises: b48ab57cf957
Create Date: 2025-03-13 18:52:16.213047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba45df612d06'
down_revision = 'b48ab57cf957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('immediate_feedback')
        batch_op.drop_column('randomize_questions')
        batch_op.drop_column('time_limit')
        batch_op.drop_column('max_attempts')
        batch_op.drop_column('deadline')
        batch_op.drop_column('passing_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passing_score', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('deadline', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('max_attempts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('time_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('randomize_questions', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('immediate_feedback', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
