"""Add ChatRoom model and chat_room_id to Message

Revision ID: bbdcc7b2749b
Revises: fa567f4d182e
Create Date: 2025-05-01 09:30:45.899314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbdcc7b2749b'
down_revision = 'fa567f4d182e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_course_id')
        batch_op.create_index(batch_op.f('ix_messages_chat_room_id'), ['chat_room_id'], unique=False)
        batch_op.drop_constraint('messages_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_rooms', ['chat_room_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_ibfk_1', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_messages_chat_room_id'))
        batch_op.create_index('ix_messages_course_id', ['course_id'], unique=False)

    # ### end Alembic commands ###
