"""Make title required in LessonSection

Revision ID: f92b30381fc2
Revises: bc59eaa1ad4a
Create Date: 2025-03-01 19:18:24.138866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92b30381fc2'
down_revision = 'bc59eaa1ad4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_section', schema=None) as batch_op:
        batch_op.drop_column('order')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
